### ISSUE TITLE
SendCommand Failure

### ISSUE THREAD

**Issue by ElektroKill** [AdvancedHacker101/C-Sharp-R.A.T-Client#11]
when I run the rat I get "Send Command Failure Object reference not set to an instance of an object."

**Comment by AdvancedHacker101** [comment]
It's probably was because I left the `IsLinuxServer` variable set to `true`, the lastest commit fixed this.  
You can give it a try and report back here with your results.

**Comment by ElektroKill** [comment]
its fixed :)

**Comment by AdvancedHacker101** [comment]
I'm happy :), closing this issue now...
