### ISSUE TITLE
Missing DLL's

### ISSUE THREAD

**Issue by briancassey** [AdvancedHacker101/C-Sharp-R.A.T-Client#8]
Do you have any plans on uploading the needed DLL's?
I can't compile any of your programs because there are missing libraries.
Thank you - Brian

**Comment by AdvancedHacker101** [comment]
Hi!
Sorry to hear you have an issue, I don't see any DLLs that aren't uploaded from my project folder.
The project dependencies are under TutClient/bin/Debug
Can you tell me the name of the DLL files missing? Or just post the error message if you want.
Looking forward to fix this issue!
**Advanced Hacking 101**

**Comment by AdvancedHacker101** [comment]
Hi!  
I'm sorry but this information is not enough for me to identify the problem you're experiencing.  
If you're still having this issue, and you have more information you can re-open this issue.
