### ISSUE TITLE
Handshake failed?

### ISSUE THREAD

**Issue by bukusgithub** [AdvancedHacker101/C-Sharp-R.A.T-Client#9]
I'm currently getting this issue when I'm trying to connect.

> System.IO.IOException: 'The handshake failed due to an unexpected packet format.'

this is the code that's giving me the error.
`
if (IsLinuxServer) { _sslClient = new SslStream(new NetworkStream(_clientSocket), false, new RemoteCertificateValidationCallback(ValidateSSLConnection), null); _sslClient.AuthenticateAsClient(""); //this is the highlighted line giving error. LaunchHearthbeat(); }`

the line that gives the error is _sslClient.AuthenticateAsClient("");
I thought maybe it was my issue with ports etc. however I have an older version of your RAT when i first started following you along way back when. that connects just fine.

**Comment by AdvancedHacker101** [comment]
Hi!
Sorry it's my bad, I pushed the code to github, while it was under development, now the code has experimental components.  
I'm working on a server that can run on linux, and the client is in linux server mode.  
You can set the [this](https://github.com/AdvancedHacker101/C-Sharp-R.A.T-Client/blob/627f73b183f06aeaf5cce2e6f99ba0ee98e9b337/TutClient/Program.cs#L306) variable to false.  This will tell the client that the server it's connecting to is a Windows server, and everything will work just like before.  
The Linux Server is currently under development, it will be pushed when it gets to a somewhat stable state.  
**Thank you** for opening this issue!

**Comment by bukusgithub** [comment]
Fantastic, works perfectly now. thank you. looking forward to see what's coming next!
